version: '3'

services:
  web:
    build: 
        context: .
        dockerfile: WebDockerfile
    ports:
      - "5000:5000"
    volumes:
      - ${EXTERNAL_LOG_LOCATION}:${INTERNAL_LOG_LOCATION}
    networks:
      logServerNetwork:
        ipv4_address: ${WEB_IP}

  server:
    build: 
        context: .
        dockerfile: ServerDockerfile
    ports:
      - "9981:9981"
    volumes:
      - ${EXTERNAL_LOG_LOCATION}:${INTERNAL_LOG_LOCATION}
    networks:
      logServerNetwork:
        ipv4_address: ${SERVER_IP}

networks:
  logServerNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16